
CREATE TABLE HOSPITAL_DATA(
HOSPITAL_NAME VARCHAR(16777216),
HOSPITAL_ID VARCHAR(16777216) PRIMARY KEY,
CITY VARCHAR(16777216),
STATE VARCHAR(16777216),
ZIPCODE VARCHAR(16777216)
);
INSERT INTO HOSPITAL_DATA VALUES ('St. Rose Dominican Hospital - Rose de Lima','659-HOS-40','Henderson','NV','89015');

INSERT INTO HOSPITAL_DATA VALUES ('Carolina Medical Center','H0071','Charlotte', 'NC' , '28203');

INSERT INTO HOSPITAL_DATA VALUES ('St. Rose Dominican Hospital - Siena','2969-HOS-41','Henderson', 'NV' , '89052');

INSERT INTO HOSPITAL_DATA VALUES ('Ascension St. Alexius| Ascension Saint Alexius Women and Children Hospital','0004994','ELGIN', 'IL' , '60169');

INSERT INTO HOSPITAL_DATA VALUES ('The Charlotte Mecklenburg Hospital','H0082','Wadesboro', 'NC' , '28170');

INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Mint_Hill_Medical_Center','H0290','Charlotte', 'NC' , '28215');

INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Ballantyne_Medical_Center','H0292','West Charlotte', 'NC' , '28277');

INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Charlotte_Orthopedic_Hospital','H0010','Charlotte', 'NC' , '28207');


INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Huntersville_Medical_Center','H0010','Huntersville', 'NC' , '28078');
INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Matthews_Medical_Center','H0270','Matthews', 'NC' , '28105');
INSERT INTO HOSPITAL_DATA VALUES ('Novant_Health_Presbyterian_Medical_Center','H0010','Charlotte', 'NC' , '28204');

INSERT INTO HOSPITAL_DATA VALUES ('Edward Hospital','003905','Naperville', 'IL' , '60504');

INSERT INTO HOSPITAL_DATA VALUES ('Elmhurst Memorial Hospital','0005751','Elmhurst', 'IL' , '60126');

INSERT INTO HOSPITAL_DATA VALUES ('Linden Oaks Hospital','0005058','Naperville', 'IL' , '60540');

INSERT INTO HOSPITAL_DATA VALUES ('CaroMont Regional Medical Center','H0105','Gastonia', 'NC' , '28054');
INSERT INTO HOSPITAL_DATA VALUES ('Touchette Regional Hospital','4523','Cahokia Heights', 'IL' , '62207');
INSERT INTO HOSPITAL_DATA VALUES ('UT Health Henderson','100428','Henderson', 'NV' , '75652');


/*
SELECT * FROM HOSPITAL_DATA;
SELECT * FROM STAGE.ALEXIUS_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.CAROLINAS_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.CHARLOTTE_MECKLENBURG;
select * from HEALTH_NAV.CORE.EDWARD_HOSPITAL;
select * from HEALTH_NAV.CORE.ELMHURST_MEMORIAL_HOSPITAL;
select * from HEALTH_NAV.CORE.LINDEN_OAKS_HOSPITAL;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_BALLANTYNE_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_CHARLOTTE_ORTHOPEDIC_HOSPITAL;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_HUNTERSVILLE_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_MATTHEWS_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_MINT_HILL_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.NOVANT_HEALTH_PRESBYTERIAN_MEDICAL_CENTER;
select * from HEALTH_NAV.CORE.ST_ROSE_DOMINICAN_HOSPITAL_ROSE_DE_LIMA;
select * from HEALTH_NAV.CORE.TOUCHETTE_REGIONAL_HOSPITAL;
select * from HEALTH_NAV.CORE.ST_ROSE_DOMINICAN_HOSPITAL_SIENA;
select * from HEALTH_NAV.CORE.UT_HEALTH_HENDERSON;
--DELETE FROM HOSPITAL_DATA WHERE hospital_name = 'Edward Hospital'
select * from hospital_data
*/