CREATE TABLE IF NOT EXISTS "HEALTH_NAV"."CORE"."INSURANCE_PROVIDERS" (
    INSURANCE_PROVIDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    PAYER_NAME VARCHAR(500)
);


MERGE INTO "HEALTH_NAV"."CORE"."INSURANCE_PROVIDERS" AS target
USING (
    WITH all_providers AS (
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".ST_ROSE_DOMINICAN_HOSPITAL_ROSE_DE_LIMA
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".CAROLINAS_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".ST_ROSE_DOMINICAN_HOSPITAL_SIENA
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".ALEXIUS_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".CHARLOTTE_MECKLENBURG
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_MINT_HILL_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_BALLANTYNE_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_CHARLOTTE_ORTHOPEDIC_HOSPITAL
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_HUNTERSVILLE_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_MATTHEWS_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".NOVANT_HEALTH_PRESBYTERIAN_MEDICAL_CENTER
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".EDWARD_HOSPITAL
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".ELMHURST_MEMORIAL_HOSPITAL
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".LINDEN_OAKS_HOSPITAL
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".CAROMONT_PART1
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".CAROMONT_PART2
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".TOUCHETTE_REGIONAL_HOSPITAL
        UNION ALL
        SELECT "PAYER_NAME" FROM "HEALTH_NAV"."CORE".UT_HEALTH_HENDERSON
        
    )
    SELECT DISTINCT PAYER_NAME
    FROM all_providers
    WHERE PAYER_NAME IS NOT NULL
      AND TRIM(PAYER_NAME) <> ''
) AS source
ON target.PAYER_NAME = source.PAYER_NAME
WHEN NOT MATCHED 
    AND source.PAYER_NAME IS NOT NULL 
    AND TRIM(source.PAYER_NAME) <> '' THEN
    INSERT (PAYER_NAME)
    VALUES (source.PAYER_NAME);
